# Generated by Django 5.2.8 on 2025-11-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawledpage',
            options={'ordering': ['-crawled_at']},
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='crawledpage',
            name='url',
            field=models.URLField(db_index=True, max_length=1000, unique=True),
        ),
        migrations.AddIndex(
            model_name='crawledpage',
            index=models.Index(fields=['-crawled_at'], name='crawler_cra_crawled_e535e3_idx'),
        ),
    ]
